<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkMFqCG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkMFqCG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkMFqCG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkMFqCG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFkMFqCG\App_KernelDevDebugContainer([
    'container.build_hash' => 'FkMFqCG',
    'container.build_id' => '547e8179',
    'container.build_time' => 1706655750,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkMFqCG');
