<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4xoXEq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4xoXEq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI4xoXEq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI4xoXEq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI4xoXEq\App_KernelDevDebugContainer([
    'container.build_hash' => 'I4xoXEq',
    'container.build_id' => '30d01cda',
    'container.build_time' => 1706662625,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4xoXEq');
